### ISSUE TITLE
Duplicate templates

### ISSUE THREAD

**Issue by nwithan8** [whallin/unraid-templates#1]
### Expected behavior

Several of your templates are duplicates of applications that already exist in the Community Apps store, including Home Assistant, Jellyfin, Homepage and Cloudflared. This unnecessarily clutters up the store. Please refer to Note 15 and Note 19 on this thread regarding contributing to the Community Apps store: https://forums.unraid.net/topic/87144-ca-application-policies-notes/

### Current behavior

N/A

### Reproduction steps

N/A

### Is there an existing issue for this?

- [X] I have searched for existing issues before opening this issue.
- [X] I have provided all relevant details to begin troubleshooting of this issue.
- [X] I have contacted the application developer(s) to confirm what I am expericing isn't only a problem on my end.

**Comment by whallin** [comment]
Thanks for reporting this to me, @nwithan8.

I've gone ahead and moved a couple of templates to a "local" directory in this repository with commit https://github.com/whallin/unraid-templates/commit/2065b220ceaebb7ba1d263352bec05bcb4ed2e16, and I hope that unlists them from the CA the next time it refreshes.

I'm pretty sure that the additional templates of mine still listed on the CA don't break Note 19, as you mentioned. However, I may be a bit unsure about Note 15. I'm confident I could show how some of my templates that touch upon Note 15 either (a) are updated to account for changes in the base image (e.g., new paths and variables) or (b) provide more customizability out of the box compared to the other pre-existing templates—if the latter is even a valid reason.

I'll happily take down more templates if they're deemed not fit under the policies. Just give me a shout, and I'll take a look.

**Comment by nwithan8** [comment]
> I've gone ahead and moved a couple of templates to a "local" directory in this repository with commit https://github.com/whallin/unraid-templates/commit/2065b220ceaebb7ba1d263352bec05bcb4ed2e16, and I hope that unlists them from the CA the next time it refreshes.

I don't believe that will work. Looking at [the logs from the latest run of the app feed](https://github.com/Squidly271/AppFeed/blob/master/log.txt#L20), the templates in "local" still got picked up. I think you'd have to put them in a folder marked "deprecated" for them to be marked as such from the store ([for example](https://github.com/Squidly271/AppFeed/blob/master/log.txt#L428)).
