### ISSUE TITLE
obsidian container gives error on boot

### ISSUE THREAD

**Issue by robbiered** [whallin/unraid-templates#2]
### Expected behavior

app starts

### Current behavior

Docker logs show this: s6-overlay-suexec: fatal: can only run as pid 1

### Reproduction steps

start container on unraid

### Relevant logs

```shell
s6-overlay-suexec: fatal: can only run as pid 1
```

### Is there an existing issue for this?

- [X] I have searched for existing issues before opening this issue.
- [X] I have provided all relevant details to begin troubleshooting of this issue.
- [X] I have contacted the application developer(s) to confirm what I am expericing isn't only a problem on my end.

**Comment by tylermiranda** [comment]
yeah this happens with the multi-scrobbler container too

**Comment by whallin** [comment]
I've gone ahead and fixed this in the most recent commit. Hopefully, it will update on the CA shortly. 

Thanks for the report :)
